# Generated by Django 2.1.7 on 2019-03-17 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 3, 17, 0, 16, 54, 556795)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='slug',
            field=models.CharField(default='slug', max_length=20),
            preserve_default=False,
        ),
    ]
