# Generated by Django 2.1.7 on 2019-03-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_auto_20190317_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='slug',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
